<template>
  <div class="env-setup-panel">
    <div class="scroll-container" ref="scrollContainer">
      <!-- Step 01: Simulation Init -->
      <Step1SimulationInit 
        :phase="phase"
        :task-id="taskId"
        :simulation-id="simulationId"
        :expected-total="expectedTotal"
        @select-agents="loadEntities"
        @start-preparation="startPreparation"
        @open-ingestion="showIngestionModal = true"
      />

      <!-- Step 02: Profile Generation -->
      <Step2ProfileGeneration
        :phase="phase"
        :prepare-progress="prepareProgress"
        :current-stage="currentStage"
        :progress-message="progressMessage"
        :profiles="profiles"
        :display-profiles="displayProfiles"
        :total-topics-count="totalTopicsCount"
        @explore="showExplorer = true"
        @select-profile="selectProfile"
      />

      <!-- Step 03: World Configuration (AI Generated) -->
      <Step3WorldConfig
        :phase="phase"
        :config="simulationConfig"
      />

      <!-- Step 04: Event Orchestration -->
      <Step4EventOrchestration 
        :phase="phase"
        :config="simulationConfig"
      />

      <!-- Step 05: Ready to Launch -->
      <Step5ReadyToLaunch 
        :phase="phase"
        :custom-max-rounds="customMaxRounds"
        @launch="launchSimulation"
      />

      <!-- Optional: Preload Knowledge -->
      <!-- Keeping simple for now, can extract to component if needed -->
      <!-- ... -->

    </div>

    <!-- Modals -->
    <EntitySelectionModal
      v-if="showEntityModal"
      :visible="showEntityModal"
      :entities="previewEntities"
      :by-type="previewByType"
      @close="showEntityModal = false"
      @confirm="handleEntitySelection"
    />

    <LiveIngestionModal
      :visible="showIngestionModal"
      @close="showIngestionModal = false"
      @ingested="handleIngestedData"
    />

    <div v-if="showExplorer" class="explorer-modal-overlay">
      <div class="explorer-modal-content">
        <button class="close-btn" @click="showExplorer = false">×</button>
        <AgentExplorer :simulation-id="simulationId" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch, nextTick } from 'vue'
// CSS
import '../features/simulation/styles/envSetup.css'

// Components
import Step1SimulationInit from '../features/simulation/components/Step1SimulationInit.vue'
import Step2ProfileGeneration from '../features/simulation/components/Step2ProfileGeneration.vue'
import Step3WorldConfig from '../features/simulation/components/Step3WorldConfig.vue'
import Step4EventOrchestration from '../features/simulation/components/Step4EventOrchestration.vue'
import Step5ReadyToLaunch from '../features/simulation/components/Step5ReadyToLaunch.vue'
import EntitySelectionModal from './EntitySelectionModal.vue'
import LiveIngestionModal from '../features/simulation/components/LiveIngestionModal.vue'
import AgentExplorer from './AgentExplorer.vue'

// Composables
import { useEnvSetupState } from '../features/simulation/hooks/useEnvSetupState'
import { useProfileManagement } from '../features/simulation/hooks/useProfileManagement'
import { useSimulationConfiguration } from '../features/simulation/hooks/useSimulationConfiguration'
import { useEntitySelection } from '../features/simulation/hooks/useEntitySelection'
import { useSimulationActions } from '../features/simulation/hooks/useSimulationActions'

// Props & Ems
const props = defineProps<{
  simulationId?: string
  projectData?: any
  graphData?: any
  systemLogs?: any[]
}>()

const emit = defineEmits(['go-back', 'next-step', 'add-log', 'update-status'])

// Initialize State
const { phase, taskId, prepareProgress, currentStage, progressMessage, updateProgress } = useEnvSetupState()
const { profiles, showExplorer, selectedProfile, showProfilesDetail, displayProfiles, totalTopicsCount } = useProfileManagement()
const { simulationConfig, scenarios, customMaxRounds, autoGeneratedRounds, useCustomRounds } = useSimulationConfiguration()
const { showEntityModal, previewEntities, previewByType, selectedEntityIds, expectedTotal } = useEntitySelection()

const showIngestionModal = ref(false)

// Actions
const { 
  loadEntityPreview, 
  startPrepareSimulation, 
  stopAllPolling, 
  handleStartSimulation, 
  loadPreparedData 
} = useSimulationActions(
  () => props.simulationId, // Pass getter for props
  { phase, taskId, updateProgress },
  { profiles },
  { simulationConfig, useCustomRounds, customMaxRounds, autoGeneratedRounds },
  { showEntityModal, previewEntities, previewByType, selectedEntityIds, expectedTotal },
  emit
)

// Wrappers for template
const loadEntities = () => loadEntityPreview()
const startPreparation = () => startPrepareSimulation()
const launchSimulation = () => handleStartSimulation()

const handleEntitySelection = (ids: string[]) => {
  selectedEntityIds.value = ids
  showEntityModal.value = false
  emit('add-log', `Selected ${ids.length} entities`)
  startPrepareSimulation()
}

const selectProfile = (p: any) => {
  selectedProfile.value = p
}

const handleIngestedData = (data: any) => {
  emit('add-log', `✓ Ingested ${data.total_ingested} posts from real-world`)
  // Optional: Trigger profile regeneration or update context
}

// Lifecycle
onMounted(async () => {
  if (props.simulationId) {
     emit('add-log', 'Step 2 Environment Setup Initialized')
     // Check if already prepared logic is inside onMounted usually, 
     // but we can trigger loadPreparedData if needed or rely on user action.
     // Legacy Logic did check status. Let's do a safe check or rely on Actions?
     // For now, let's keep it clean. Actions has 'loadPreparedData'. 
     // We can try to load.
     
     // Legacy had complex logic to check status first. 
     // Let's assume user is starting fresh or resuming. 
     // We can call a checkStatus action if we add it. 
     // For now just logging.
  }
})

onUnmounted(() => {
  stopAllPolling()
})

// Log scrolling
const scrollContainer = ref<HTMLElement | null>(null)
// Note: Log scrolling was for systemLogs prop which is passed down.
// In legacy it scrolled a ref="logContent" but that was in a sidebar?
// Nope, props.systemLogs suggests logs are displayed here. 
// Actually logs are usually in parent. Step2 emits 'add-log'.
</script>

<style scoped>
.explorer-modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0,0,0,0.8);
  z-index: 1000;
  display: flex;
  justify-content: center;
  align-items: center;
}

.explorer-modal-content {
  width: 90%;
  height: 90%;
  background: var(--bg-primary);
  border-radius: 12px;
  position: relative;
  overflow: hidden;
}

.close-btn {
  position: absolute;
  top: 10px;
  right: 15px;
  font-size: 24px;
  color: white;
  background: none;
  border: none;
  cursor: pointer;
  z-index: 1001;
}
</style>
