import { ref, computed } from 'vue'
import type { SimulationConfig } from '../types/envSetup'

export function useSimulationConfiguration() {
    const simulationConfig = ref<SimulationConfig | null>(null)

    // Scenario State
    const scenarios = ref<string[]>([])
    const selectedScenario = ref('')
    const loadingScenarios = ref(false)

    // Simulation rounds count configuration
    const useCustomRounds = ref(false)
    const customMaxRounds = ref(40)

    const autoGeneratedRounds = computed(() => {
        if (!simulationConfig.value?.time_config) {
            return null
        }
        const totalHours = simulationConfig.value.time_config.total_simulation_hours
        const minutesPerRound = simulationConfig.value.time_config.minutes_per_round
        if (!totalHours || !minutesPerRound) {
            return null
        }
        const calculatedRounds = Math.floor((totalHours * 60) / minutesPerRound)
        return Math.max(calculatedRounds, 40)
    })

    return {
        simulationConfig,
        scenarios,
        selectedScenario,
        loadingScenarios,
        useCustomRounds,
        customMaxRounds,
        autoGeneratedRounds
    }
}
